// AUTO-GENERATED by @hono/inertia/vite. Do not edit.
import type app from "./server";

export type PageName = "Home";

declare module "@hono/inertia" {
  interface InertiaPages {
    Home: unknown;
  }
  interface AppRegistry {
    app: typeof app;
  }
}

export type { PageProps } from "@hono/inertia";
